// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0dbj6PxFAfIHDxLSeFtA7I3NN1YW4ARg',
    appId: '1:884509450380:web:7d79a2af3bf674ec371ba9',
    messagingSenderId: '884509450380',
    projectId: 'lat-flutter-3582e',
    authDomain: 'lat-flutter-3582e.firebaseapp.com',
    storageBucket: 'lat-flutter-3582e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBS4qWYBfCOIW4kFr7eZwVfy7Vo_zQuCM',
    appId: '1:884509450380:android:06208288045f3ce4371ba9',
    messagingSenderId: '884509450380',
    projectId: 'lat-flutter-3582e',
    storageBucket: 'lat-flutter-3582e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8yHj_lY3oxPtXneaQRUuRT8gbZZ_ESk',
    appId: '1:884509450380:ios:8c0204a3ef325edb371ba9',
    messagingSenderId: '884509450380',
    projectId: 'lat-flutter-3582e',
    storageBucket: 'lat-flutter-3582e.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp8yHj_lY3oxPtXneaQRUuRT8gbZZ_ESk',
    appId: '1:884509450380:ios:8c0204a3ef325edb371ba9',
    messagingSenderId: '884509450380',
    projectId: 'lat-flutter-3582e',
    storageBucket: 'lat-flutter-3582e.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaanFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0dbj6PxFAfIHDxLSeFtA7I3NN1YW4ARg',
    appId: '1:884509450380:web:937396ec8f8c6f2c371ba9',
    messagingSenderId: '884509450380',
    projectId: 'lat-flutter-3582e',
    authDomain: 'lat-flutter-3582e.firebaseapp.com',
    storageBucket: 'lat-flutter-3582e.firebasestorage.app',
  );
}
